name: golang

on:
  push:
    paths:
      - '.github/workflows/golang.yml'
      - 'golang/**'
  pull_request:
    paths:
      - '.github/workflows/golang.yml'
      - 'golang/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Test
        uses: docker/build-push-action@v2
        with:
          context: ./golang
          file: ./golang/Dockerfile
          platforms: ${{ steps.buildx.outputs.platforms }}
