name: test

on:
  push:
    branches:
      - 'master'
      - 'v2'
  pull_request:
    branches:
      - 'master'
      - 'v2'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      -
        name: Base
        run: |
          docker buildx bake base --progress=plain
      -
        name: Test
        run: |
          docker buildx bake test --progress=plain

